Repository AY2122S1-CS2103T-F12-4/tp, pull requests merged in 2021-10, with the labels that each got.

#29 Update AboutUs
  docs/AboutUs.md
Labels: type.Task :exclamation:, priority.High :1st_place_medal:

#31 Update AboutUs to include basic information.
  docs/AboutUs.md
  docs/images/Morrow1ndy.png
  docs/images/holmesjj.png
  docs/images/mukundrs.png
  docs/images/stephanie-csy.png
  docs/images/zzybluebell.png
Labels: type.Task :exclamation:, priority.High :1st_place_medal:

#24 Update the DG: User stories, Glossary, NFRs, Use cases
  docs/DeveloperGuide.md
Labels: type.Task :exclamation:, priority.High :1st_place_medal:

#36 Update AboutUs with basic information.
  docs/AboutUs.md
  docs/images/morrow1ndy.png
Labels: type.Task :exclamation:, priority.High :1st_place_medal:

#37 Update first half of User Guide
  docs/UserGuide.md
Labels: type.Task :exclamation:

#40 Update format of UG
  docs/UserGuide.md
  docs/images/ezFoodieLogo.png
Labels: type.Bug :bee:, priority.High :1st_place_medal:

#41 Fix small bug of UG
  docs/UserGuide.md
Labels: type.Bug :bee:, priority.High :1st_place_medal:

#43 Fix small bugs of AboutUs
  docs/AboutUs.md
  docs/images/mukundrs.png
Labels: type.Bug :bee:, priority.High :1st_place_medal:

#54 README.md and index.md 3nd version
  README.md
  docs/index.md
Labels: type.Task :exclamation:, priority.Medium :2nd_place_medal:

#62 Update UG with changes to edit function
  docs/UserGuide.md
Labels: type.Task :exclamation:, priority.Medium :2nd_place_medal:

#75 Update Transaction
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/member/Member.java
  src/main/java/seedu/address/model/transaction/Transaction.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedMember.java
  src/test/data/JsonEzFoodieStorageTest/invalidAndValidMemberEzFoodie.json
  src/test/data/JsonSerializableEzFoodieTest/typicalMembersEzFoodie.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EzFoodieParserTest.java
  src/test/java/seedu/address/model/transaction/TransactionTest.java
  src/test/java/seedu/address/storage/JsonAdaptedMemberTest.java
  src/test/java/seedu/address/testutil/EditMemberDescriptorBuilder.java
  src/test/java/seedu/address/testutil/MemberBuilder.java
  src/test/java/seedu/address/testutil/MemberUtil.java
  src/test/java/seedu/address/testutil/TypicalMembers.java
Labels: type.Story :label:, priority.High :1st_place_medal:

#72 Add Logout
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/commons/status/ExecutionStatus.java
  src/main/java/seedu/address/commons/status/LoginStatus.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/LogoutCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EzFoodieParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/LogoutCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EzFoodieParserTest.java
Labels: type.Story :label:, priority.High :1st_place_medal:

#77 Update Delete
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EzFoodieParserTest.java
Labels: type.Story :label:, priority.High :1st_place_medal:

#78 Update List
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/EzFoodieParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/EzFoodieParserTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
Labels: type.Story :label:, priority.High :1st_place_medal:

#81 Update View
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/commons/status/LoginStatus.java
  src/main/java/seedu/address/commons/util/DateTimeUtil.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/commands/LogoutCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/member/Credit.java
  src/main/java/seedu/address/model/member/Member.java
  src/main/java/seedu/address/model/member/Tier.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedMember.java
  src/main/java/seedu/address/ui/MemberCard.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/view/MemberListCard.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/test/data/JsonEzFoodieStorageTest/invalidAndValidMemberEzFoodie.json
  src/test/data/JsonEzFoodieStorageTest/invalidMemberEzFoodie.json
  src/test/data/JsonSerializableEzFoodieTest/duplicateMemberEzFoodie.json
  src/test/data/JsonSerializableEzFoodieTest/invalidMemberEzFoodie.json
  src/test/data/JsonSerializableEzFoodieTest/typicalMembersEzFoodie.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/LogoutCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EzFoodieParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedMemberTest.java
  src/test/java/seedu/address/testutil/MemberBuilder.java
  src/test/java/seedu/address/testutil/TypicalMembers.java
Labels: type.Task :exclamation:, priority.High :1st_place_medal:

#79 Sort Credit
  src/main/java/seedu/address/commons/status/SortStatus.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EzFoodieParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/member/Credit.java
  src/main/java/seedu/address/model/member/CreditSortComparator.java
  src/main/java/seedu/address/model/transaction/Transaction.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
Labels: type.Story :label:, priority.High :1st_place_medal:

#83 Update Edit
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/exceptions/DataConversionException.java
  src/main/java/seedu/address/commons/exceptions/PermissionException.java
  src/main/java/seedu/address/commons/status/LoginStatus.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EzFoodieParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EzFoodieParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Story :label:, priority.High :1st_place_medal:

#85 Add Assertions
  build.gradle
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
Labels: type.Task :exclamation:, priority.High :1st_place_medal:

#71 Add Members
  config/checkstyle/checkstyle.xml
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddMemberCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EzFoodieParser.java
  src/main/java/seedu/address/logic/parser/Prefix.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EzFoodieParserTest.java
  src/test/java/seedu/address/testutil/MemberUtil.java
Labels: type.Story :label:, priority.High :1st_place_medal:
